site_name: Med Grabber

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      toggle:
        icon: material/brightness-7
        name: Tema escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      toggle:
        icon: material/brightness-4
        name: Tema claro
  features:
    - tabs
    - navigation.section

nav:
  - Documento de Arquitetura: documento_arquitetura.md
  - Documento de Requisitos: documento_requisito.md
  - Documento de Visão: documento_visão.md
  <p align='center'>
    <img src='./assets/documento_visao/RichPicture_Davi.png'>
    <figcaption align='center'>
        <b>
            <a href='./assets/documento_visao/RichPicture_Davi.png''>
               Figura 2: Rich Picture V1
            </a>
        </b>   
        <br>
        <small>Autor: <a href='https://github.com/DaviMatheus'>Davi Matheus</a>, 2023.</small>
    </figcaption>
</p>
